# This file was generated by GoReleaser. DO NOT EDIT.
cask "amuxify" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "38cf725b560baac3ce5e9e66cf03451e113c12a31b40b2b1cb025dc27ae4f2f4"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9c229c69fc00c799f09afefd71bae18521a1ddfd5c34c576d8a763ed3008004"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "35abb001f52a4135eeb16a3a4cbef6629b2a9cf83c962a706f2c731240d09814"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6626ab993957177def6c2f516f506c40380e7456ca7dd1fbdb69b214fc186324"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_amd64.tar.gz"
    end
  end

  name "amuxify"
  desc "The ingest gate for self-hosted media"
  homepage "https://amuxify.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "mkvtoolnix",
    ]

  binary "amuxify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amuxify"]
    end
  end

  # No zap stanza required
end
