# This file was generated by GoReleaser. DO NOT EDIT.
cask "amuxify" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/amuxify"]
    end
  end

  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "85356031840e936c5520973c9bd53c4b60051a0050212bfe7f639445f8187c59"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e48019dd08e298267ded54b2e8362eac67ce74dc56538f77f9162f0374dd17e"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "be7b90885e2a2402e19d5139e901919bb6d2a6c20b4e617bbc11ac244450e2c8"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "22a8773304d91824ac0ef920c12b8c7335209f77ed60237c7128ce3bcd640852"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_amd64.tar.gz"
    end
  end

  name "amuxify"
  desc "The ingest gate for self-hosted media"
  homepage "https://amuxify.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "mkvtoolnix",
    ]

  binary "amuxify"

  # No zap stanza required
end
