# This file was generated by GoReleaser. DO NOT EDIT.
cask "amuxify" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "6eaa17a83b1f2214f994390303d32ddaf8290f28c6400e5aee1141c9eacabc10"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "335270e0390e3f9e4ff10e910566def6b0d9a553994a279b20e2b7890e1a9050"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "218713c1f28a7e653395cc3e8fbcba8d0abac938d81b745ce70c1b0290a39141"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b7e767d3665c992c73251c1539dac20a0668447c0c96b8ce5ee2b37c5deae9f"
      url "https://github.com/amuxify/amuxify/releases/download/v#{version}/amuxify_#{version}_linux_amd64.tar.gz"
    end
  end

  name "amuxify"
  desc "The ingest gate for self-hosted media"
  homepage "https://amuxify.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "mkvtoolnix",
    ]

  binary "amuxify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amuxify"]
    end
  end

  # No zap stanza required
end
